name: Docs Generator 🤖
on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Enter a message for this deployment'
        required: true
        default: 'Manual deployment of documentation'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.APP_GOOGLE_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./composeApp/google-services.json
      - name: Creating Local.Properties
        env:
          FIREBASE_WEB_CLIENT_ID: ${{ secrets.FIREBASE_WEB_CLIENT_ID }}
        run: |
          echo "firebaseWebClient=${FIREBASE_WEB_CLIENT_ID}" >> ./local.properties
      - name: Generate Dokka docs
        run: ./gradlew dokkaHtmlMultiModule
      - name: Copy docs to docs/docs
        run: |
          cp -r build/dokka/htmlMultiModule docs/docs/api-references
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-simple-hooks
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Navigate and Build
        run: |
          cd generated
          ls -la
          mkdocs gh-deploy --force --message "${{ github.event.inputs.deploy_message }}"
      
